import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

@WebServlet("/api/stations/add")
public class AddStationServlet extends HttpServlet {
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("application/json; charset=UTF-8");
        PrintWriter out = response.getWriter();
        
        try {
            // Get station details from request
            String name = request.getParameter("name");
            double latitude = Double.parseDouble(request.getParameter("latitude"));
            double longitude = Double.parseDouble(request.getParameter("longitude"));
            String address = request.getParameter("address");
            int totalSockets = Integer.parseInt(request.getParameter("totalSockets"));
            int availableSockets = Integer.parseInt(request.getParameter("availableSockets"));
            double powerOutput = Double.parseDouble(request.getParameter("powerOutput"));
            double pricePerHour = Double.parseDouble(request.getParameter("pricePerHour"));
            String status = request.getParameter("status");
            String description = request.getParameter("description");
            
            // Validate required fields
            if (name == null || name.trim().isEmpty()) {
                response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
                out.print("{\"success\":false,\"message\":\"充电站名称是必填项\"}");
                return;
            }
            
            if (address == null || address.trim().isEmpty()) {
                response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
                out.print("{\"success\":false,\"message\":\"充电站地址是必填项\"}");
                return;
            }
            
            if (status == null || status.trim().isEmpty()) {
                status = "ACTIVE"; // Default status
            }
            
            if (description == null) {
                description = "";
            }
            
            // Validate numeric values
            if (totalSockets < 0) {
                response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
                out.print("{\"success\":false,\"message\":\"总插座数不能为负数\"}");
                return;
            }
            
            if (availableSockets < 0 || availableSockets > totalSockets) {
                response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
                out.print("{\"success\":false,\"message\":\"可用插座数必须在0到总插座数之间\"}");
                return;
            }
            
            if (powerOutput < 0) {
                response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
                out.print("{\"success\":false,\"message\":\"功率不能为负数\"}");
                return;
            }
            
            if (pricePerHour < 0) {
                response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
                out.print("{\"success\":false,\"message\":\"每小时价格不能为负数\"}");
                return;
            }
            
            // Create new charging station
            ChargingStation station = new ChargingStation(
                0, // ID will be generated by database
                name.trim(),
                latitude,
                longitude,
                address.trim(),
                totalSockets,
                availableSockets,
                powerOutput,
                pricePerHour,
                status,
                description
            );
            
            // Add station through manager
            ChargingStationManager manager = ChargingStationManager.getInstance();
            if (manager.addChargingStation(station)) {
                response.setStatus(HttpServletResponse.SC_OK);
                out.print("{\"success\":true,\"message\":\"充电站添加成功\",\"stationId\":" + station.getStationId() + "}");
            } else {
                response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
                out.print("{\"success\":false,\"message\":\"添加充电站失败\"}");
            }
        } catch (NumberFormatException e) {
            response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
            out.print("{\"success\":false,\"message\":\"数值字段格式错误\"}");
        } catch (Exception e) {
            response.setStatus(HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
            out.print("{\"success\":false,\"message\":\"服务器错误: " + e.getMessage() + "\"}");
        }
    }
    
    protected void doOptions(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setStatus(HttpServletResponse.SC_OK);
    }
}